### ISSUE TITLE
awsmobile run does not work on windows

### ISSUE THREAD

**Issue by kamipatel** [awslabs/aws-mobile-react-sample#18]
I tried few times and can confirm there is some issue on windows. awsmobile run does nothing from command line. It does work from Mac though. Thanks!

**Comment by kamipatel** [comment]
Not an issue

**Comment by otint** [comment]
did this get resolved? `awsmobile run` doesn't work for me on Windows 10, get this error:
```executing frontend start command ...
frontend start command execution error:
{ Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'run-script', 'start' ] }
